version: 2.1

orbs:
    node: circleci/node@5.0.0
    php: circleci/php@1.1

jobs:
    lint-and-test:
        docker:
            - image: cimg/php:8.1-node
        steps:
            - checkout
            - node/install-packages
            - php/install-packages
            - run:
                  name: Lint JavaScript
                  command: npm run lint:js
            - run:
                  name: Lint CSS
                  command: npm run lint:css
            - run:
                  name: Lint PHP
                  command: composer run-script lint
            - run:
                  name: PHP Static Analysis
                  command: composer run-script analyze
            - run:
                  name: PHP Unit Tests
                  command: composer run-script test
            - run:
                  name: Build
                  command: npm run build

workflows:
    version: 2
    build-test:
        jobs:
            - lint-and-test
